-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler version: 1.1.0-beta1
-- PostgreSQL version: 16.0
-- Project Site: pgmodeler.io
-- Model Author: ---
-- -- object: soundtracks_user | type: ROLE --
-- -- DROP ROLE IF EXISTS soundtracks_user;
-- CREATE ROLE soundtracks_user WITH 
-- 	SUPERUSER
-- 	CREATEDB
-- 	CREATEROLE
-- 	INHERIT
-- 	LOGIN
-- 	REPLICATION
-- 	BYPASSRLS
-- 	 PASSWORD '********';
-- -- ddl-end --
-- 

-- Database creation must be performed outside a multi lined SQL file. 
-- These commands were put in this file only as a convenience.
-- 
-- object: soundtracks | type: DATABASE --
-- DROP DATABASE IF EXISTS soundtracks;
CREATE DATABASE soundtracks
	ENCODING = 'UTF8'
	LC_COLLATE = 'en_US.utf8'
	LC_CTYPE = 'en_US.utf8'
	TABLESPACE = pg_default
	OWNER = soundtracks_user;
-- ddl-end --


-- object: public.artist_seq | type: SEQUENCE --
-- DROP SEQUENCE IF EXISTS public.artist_seq CASCADE;
CREATE SEQUENCE public.artist_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY NONE;

-- ddl-end --
ALTER SEQUENCE public.artist_seq OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.artist_artist_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.artist_artist_id_seq CASCADE;
-- CREATE SEQUENCE public.artist_artist_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.artist_artist_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.artist | type: TABLE --
-- DROP TABLE IF EXISTS public.artist CASCADE;
CREATE TABLE public.artist (
	artist_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	artist_name character varying(255),
	artist_genre character varying(255),
	artist_country character varying(255),
	artist_description text,
	CONSTRAINT artist_pk PRIMARY KEY (artist_id)
);
-- ddl-end --
ALTER TABLE public.artist OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.event_event_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.event_event_id_seq CASCADE;
-- CREATE SEQUENCE public.event_event_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.event_event_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.event | type: TABLE --
-- DROP TABLE IF EXISTS public.event CASCADE;
CREATE TABLE public.event (
	event_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	event_name character varying(255),
	event_date date,
	event_start time,
	event_entry time,
	event_price numeric(7,2),
	event_type character varying(255),
	event_description text,
	location_id_location bigint,
	CONSTRAINT event_pk PRIMARY KEY (event_id)
);
-- ddl-end --
ALTER TABLE public.event OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.location_location_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.location_location_id_seq CASCADE;
-- CREATE SEQUENCE public.location_location_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.location_location_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.location | type: TABLE --
-- DROP TABLE IF EXISTS public.location CASCADE;
CREATE TABLE public.location (
	location_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	location_name character varying(255),
	location_address character varying(255),
	location_postal_code character varying(20),
	location_city character varying(255),
	location_country character varying(255),
	location_capacity integer,
	location_description text,
	CONSTRAINT location_pk PRIMARY KEY (location_id)
);
-- ddl-end --
ALTER TABLE public.location OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.performance_rating_performance_rating_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.performance_rating_performance_rating_id_seq CASCADE;
-- CREATE SEQUENCE public.performance_rating_performance_rating_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.performance_rating_performance_rating_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.performance_rating | type: TABLE --
-- DROP TABLE IF EXISTS public.performance_rating CASCADE;
CREATE TABLE public.performance_rating (
	performance_rating_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	performance_average_rating numeric(3,2),
	performance_quality numeric(3,2),
	sound_quality numeric(3,2),
	set_length numeric(3,2),
	track_selection numeric(3,2),
	visual_show numeric(3,2),
	performance_rating_comments text,
	performance_id_performance bigint,
	personal_event_rating_id_personal_event_rating bigint,
	CONSTRAINT performance_rating_pk PRIMARY KEY (performance_rating_id)
);
-- ddl-end --
ALTER TABLE public.performance_rating OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.personal_event_rating_personal_event_rating_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.personal_event_rating_personal_event_rating_id_seq CASCADE;
-- CREATE SEQUENCE public.personal_event_rating_personal_event_rating_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.personal_event_rating_personal_event_rating_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.personal_event_rating | type: TABLE --
-- DROP TABLE IF EXISTS public.personal_event_rating CASCADE;
CREATE TABLE public.personal_event_rating (
	personal_event_rating_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	personal_event_average_rating numeric(3,2),
	personal_event_rating_comments text,
	person_id_person bigint,
	event_rating_id_event_rating bigint,
	performance_rating_id_performance_rating bigint,
	event_id_event bigint,
	personal_event_atmosphere_rating numeric(3,2),
	personal_event_gastronomy_rating numeric(3,2),
	personal_event_location_rating numeric(3,2),
	personal_event_performance_rating numeric(3,2),
	personal_event_restroom_rating numeric(3,2),
	personal_event_security_rating numeric(3,2),
	personal_event_sound_rating numeric(3,2),
	personal_event_wardrobe_rating numeric(3,2),
	atmosphere_rating numeric(3,2),
	gastronomy_rating numeric(3,2),
	location_rating numeric(3,2),
	performance_rating numeric(3,2),
	restroom_rating numeric(3,2),
	security_rating numeric(3,2),
	sound_rating numeric(3,2),
	wardrobe_rating numeric(3,2),
	atmosphere_crowd_engagement numeric(3,2),
	atmosphere_event_decorations numeric(3,2),
	atmosphere_event_vibe numeric(3,2),
	atmosphere_light_and_visuals numeric(3,2),
	atmosphere_staff_friendliness numeric(3,2),
	gastronomy_food_quality numeric(3,2),
	gastronomy_food_variety numeric(3,2),
	gastronomy_food_prices numeric(3,2),
	gastronomy_drink_variety numeric(3,2),
	gastronomy_drink_quality numeric(3,2),
	gastronomy_drink_prices numeric(3,2),
	gastronomy_staff_efficiency numeric(3,2),
	gastronomy_staff_friendliness numeric(3,2),
	location_accessibility numeric(3,2),
	location_size numeric(3,2),
	location_area numeric(3,2),
	location_equipment numeric(3,2),
	location_ambience numeric(3,2),
	location_cleanliness numeric(3,2),
	location_staff numeric(3,2),
	restroom_cleanliness numeric(3,2),
	restroom_accessibility numeric(3,2),
	restroom_supplies numeric(3,2),
	restroom_size numeric(3,2),
	security_staff_friendliness numeric(3,2),
	security_staff_competence numeric(3,2),
	security_sense_of_security numeric(3,2),
	sound_overall_quality numeric(3,2),
	sound_loudness numeric(3,2),
	sound_technical_issues numeric(3,2),
	sound_room_acoustics numeric(3,2),
	wardrobe_price numeric(3,2),
	wardrobe_staff_efficiency numeric(3,2),
	wardrobe_staff_friendliness numeric(3,2),
	wardrobe_quality numeric(3,2),
	CONSTRAINT personal_event_rating_pk PRIMARY KEY (personal_event_rating_id),
	CONSTRAINT personal_event_rating_uq UNIQUE (performance_rating_id_performance_rating)
);
-- ddl-end --
ALTER TABLE public.personal_event_rating OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.location_rating_location_rating_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.location_rating_location_rating_id_seq CASCADE;
-- CREATE SEQUENCE public.location_rating_location_rating_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.location_rating_location_rating_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.location_rating | type: TABLE --
-- DROP TABLE IF EXISTS public.location_rating CASCADE;
CREATE TABLE public.location_rating (
	location_rating_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	location_average_rating numeric(3,2),
	location_size numeric(3,2),
	location_area numeric(3,2),
	location_accessibility numeric(3,2),
	location_equipment numeric(3,2),
	location_ambience numeric(3,2),
	location_cleanliness numeric(3,2),
	location_staff numeric(3,2),
	location_rating_comments text,
	location_id_location bigint,
	personal_event_rating_id_personal_event_rating bigint,
	CONSTRAINT location_rating_pk PRIMARY KEY (location_rating_id),
	CONSTRAINT location_rating_uq UNIQUE (personal_event_rating_id_personal_event_rating)
);
-- ddl-end --
ALTER TABLE public.location_rating OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.restroom_rating_restroom_rating_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.restroom_rating_restroom_rating_id_seq CASCADE;
-- CREATE SEQUENCE public.restroom_rating_restroom_rating_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.restroom_rating_restroom_rating_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.restroom_rating | type: TABLE --
-- DROP TABLE IF EXISTS public.restroom_rating CASCADE;
CREATE TABLE public.restroom_rating (
	restroom_rating_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	restroom_average_rating numeric(3,2),
	restroom_cleanliness numeric(3,2),
	restroom_accessibility numeric(3,2),
	restroom_supplies numeric(3,2),
	restroom_size numeric(3,2),
	restroom_rating_comments text,
	personal_event_rating_id_personal_event_rating bigint,
	CONSTRAINT restroom_rating_pk PRIMARY KEY (restroom_rating_id),
	CONSTRAINT restroom_rating_uq UNIQUE (personal_event_rating_id_personal_event_rating)
);
-- ddl-end --
ALTER TABLE public.restroom_rating OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.security_rating_security_rating_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.security_rating_security_rating_id_seq CASCADE;
-- CREATE SEQUENCE public.security_rating_security_rating_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.security_rating_security_rating_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.security_rating | type: TABLE --
-- DROP TABLE IF EXISTS public.security_rating CASCADE;
CREATE TABLE public.security_rating (
	security_rating_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	security_average_rating numeric(3,2),
	staff_friendliness numeric(3,2),
	staff_competence numeric(3,2),
	sense_of_security numeric(3,2),
	security_rating_comments text,
	personal_event_rating_id_personal_event_rating bigint,
	CONSTRAINT security_rating_pk PRIMARY KEY (security_rating_id),
	CONSTRAINT security_rating_uq UNIQUE (personal_event_rating_id_personal_event_rating)
);
-- ddl-end --
ALTER TABLE public.security_rating OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.sound_rating_sound_rating_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.sound_rating_sound_rating_id_seq CASCADE;
-- CREATE SEQUENCE public.sound_rating_sound_rating_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.sound_rating_sound_rating_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.sound_rating | type: TABLE --
-- DROP TABLE IF EXISTS public.sound_rating CASCADE;
CREATE TABLE public.sound_rating (
	sound_rating_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	sound_average_rating numeric(3,2),
	sound_overall_quality numeric(3,2),
	sound_loudness numeric(3,2),
	sound_technical_issues numeric(3,2),
	sound_room_acoustics numeric(3,2),
	sound_rating_comments text,
	personal_event_rating_id_personal_event_rating bigint,
	CONSTRAINT sound_rating_pk PRIMARY KEY (sound_rating_id),
	CONSTRAINT sound_rating_uq UNIQUE (personal_event_rating_id_personal_event_rating)
);
-- ddl-end --
ALTER TABLE public.sound_rating OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.wardrobe_rating_wardrobe_rating_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.wardrobe_rating_wardrobe_rating_id_seq CASCADE;
-- CREATE SEQUENCE public.wardrobe_rating_wardrobe_rating_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.wardrobe_rating_wardrobe_rating_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.wardrobe_rating | type: TABLE --
-- DROP TABLE IF EXISTS public.wardrobe_rating CASCADE;
CREATE TABLE public.wardrobe_rating (
	wardrobe_rating_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	wardrobe_average_rating numeric(3,2),
	wardrobe_price numeric(3,2),
	wardrobe_staff_efficiency numeric(3,2),
	wardrobe_staff_friendliness numeric(3,2),
	wardrobe_quality numeric(3,2),
	wardrobe_rating_comments text,
	personal_event_rating_id_personal_event_rating bigint,
	CONSTRAINT sound_rating_pk_cp PRIMARY KEY (wardrobe_rating_id),
	CONSTRAINT wardrobe_rating_uq UNIQUE (personal_event_rating_id_personal_event_rating)
);
-- ddl-end --
ALTER TABLE public.wardrobe_rating OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.event_rating_event_rating_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.event_rating_event_rating_id_seq CASCADE;
-- CREATE SEQUENCE public.event_rating_event_rating_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.event_rating_event_rating_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.event_rating | type: TABLE --
-- DROP TABLE IF EXISTS public.event_rating CASCADE;
CREATE TABLE public.event_rating (
	event_rating_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	event_average_rating numeric(3,2),
	atmosphere_average_rating numeric(3,2),
	gastronomy_average_rating numeric(3,2),
	location_average_rating numeric(3,2),
	performance_average_rating numeric(3,2),
	restroom_average_rating numeric(3,2),
	security_average_rating numeric(3,2),
	sound_average_rating numeric(3,2),
	wardrobe_average_rating numeric(3,2),
	event_id_event bigint,
	CONSTRAINT event_rating_pk PRIMARY KEY (event_rating_id),
	CONSTRAINT event_rating_uq UNIQUE (event_id_event),
	CONSTRAINT unique_event_rating UNIQUE (event_id_event)
);
-- ddl-end --
ALTER TABLE public.event_rating OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.person_person_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.person_person_id_seq CASCADE;
-- CREATE SEQUENCE public.person_person_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.person_person_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.person | type: TABLE --
-- DROP TABLE IF EXISTS public.person CASCADE;
CREATE TABLE public.person (
	person_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	user_name character varying(255),
	review_count integer,
	event_count integer,
	review_score numeric(3,2),
	user_password character varying(255),
	CONSTRAINT person_pk PRIMARY KEY (person_id)
);
-- ddl-end --
ALTER TABLE public.person OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.gastronomy_rating_gastronomy_rating_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.gastronomy_rating_gastronomy_rating_id_seq CASCADE;
-- CREATE SEQUENCE public.gastronomy_rating_gastronomy_rating_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.gastronomy_rating_gastronomy_rating_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.gastronomy_rating | type: TABLE --
-- DROP TABLE IF EXISTS public.gastronomy_rating CASCADE;
CREATE TABLE public.gastronomy_rating (
	gastronomy_rating_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	gastronomy_average_rating numeric(3,2),
	gastronomy_food_variety numeric(3,2),
	gastronomy_food_quality numeric(3,2),
	gastronomy_food_prices numeric(3,2),
	gastronomy_drink_variety numeric(3,2),
	gastronomy_drink_quality numeric(3,2),
	gastronomy_drink_prices numeric(3,2),
	gastronomy_staff_efficiency numeric(3,2),
	gastronomy_staff_friendliness numeric(3,2),
	gastronomy_rating_comments text,
	personal_event_rating_id_personal_event_rating bigint,
	CONSTRAINT gastronomy_rating_pk PRIMARY KEY (gastronomy_rating_id),
	CONSTRAINT gastronomy_rating_uq UNIQUE (personal_event_rating_id_personal_event_rating)
);
-- ddl-end --
ALTER TABLE public.gastronomy_rating OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.atmosphere_rating_atmosphere_rating_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.atmosphere_rating_atmosphere_rating_id_seq CASCADE;
-- CREATE SEQUENCE public.atmosphere_rating_atmosphere_rating_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.atmosphere_rating_atmosphere_rating_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.atmosphere_rating | type: TABLE --
-- DROP TABLE IF EXISTS public.atmosphere_rating CASCADE;
CREATE TABLE public.atmosphere_rating (
	atmosphere_rating_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	atmosphere_average_rating numeric(3,2),
	event_vibe numeric(3,2),
	crowd_engagement numeric(3,2),
	light_and_visuals numeric(3,2),
	event_decorations numeric(3,2),
	staff_friendliness numeric(3,2),
	atmosphere_rating_comments text,
	personal_event_rating_id_personal_event_rating bigint,
	CONSTRAINT atmosphere_rating_pk PRIMARY KEY (atmosphere_rating_id),
	CONSTRAINT atmosphere_rating_uq UNIQUE (personal_event_rating_id_personal_event_rating)
);
-- ddl-end --
ALTER TABLE public.atmosphere_rating OWNER TO soundtracks_user;
-- ddl-end --

-- -- object: public.performance_performance_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.performance_performance_id_seq CASCADE;
-- CREATE SEQUENCE public.performance_performance_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 9223372036854775807
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- 
-- -- ddl-end --
-- ALTER SEQUENCE public.performance_performance_id_seq OWNER TO soundtracks_user;
-- -- ddl-end --
-- 
-- object: public.performance | type: TABLE --
-- DROP TABLE IF EXISTS public.performance CASCADE;
CREATE TABLE public.performance (
	performance_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	performance_duration interval,
	performance_type character varying(255),
	performance_genre character varying(255),
	artist_id_artist bigint,
	event_id_event bigint,
	performance_rating_id_performance_rating bigint,
	CONSTRAINT performance_pk PRIMARY KEY (performance_id)
);
-- ddl-end --
ALTER TABLE public.performance OWNER TO soundtracks_user;
-- ddl-end --

-- object: location_fk | type: CONSTRAINT --
-- ALTER TABLE public.event DROP CONSTRAINT IF EXISTS location_fk CASCADE;
ALTER TABLE public.event ADD CONSTRAINT location_fk FOREIGN KEY (location_id_location)
REFERENCES public.location (location_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: performance_fk | type: CONSTRAINT --
-- ALTER TABLE public.performance_rating DROP CONSTRAINT IF EXISTS performance_fk CASCADE;
ALTER TABLE public.performance_rating ADD CONSTRAINT performance_fk FOREIGN KEY (performance_id_performance)
REFERENCES public.performance (performance_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: personal_event_rating_fk | type: CONSTRAINT --
-- ALTER TABLE public.performance_rating DROP CONSTRAINT IF EXISTS personal_event_rating_fk CASCADE;
ALTER TABLE public.performance_rating ADD CONSTRAINT personal_event_rating_fk FOREIGN KEY (personal_event_rating_id_personal_event_rating)
REFERENCES public.personal_event_rating (personal_event_rating_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: person_fk | type: CONSTRAINT --
-- ALTER TABLE public.personal_event_rating DROP CONSTRAINT IF EXISTS person_fk CASCADE;
ALTER TABLE public.personal_event_rating ADD CONSTRAINT person_fk FOREIGN KEY (person_id_person)
REFERENCES public.person (person_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: event_rating_fk | type: CONSTRAINT --
-- ALTER TABLE public.personal_event_rating DROP CONSTRAINT IF EXISTS event_rating_fk CASCADE;
ALTER TABLE public.personal_event_rating ADD CONSTRAINT event_rating_fk FOREIGN KEY (event_rating_id_event_rating)
REFERENCES public.event_rating (event_rating_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: performance_rating_fk | type: CONSTRAINT --
-- ALTER TABLE public.personal_event_rating DROP CONSTRAINT IF EXISTS performance_rating_fk CASCADE;
ALTER TABLE public.personal_event_rating ADD CONSTRAINT performance_rating_fk FOREIGN KEY (performance_rating_id_performance_rating)
REFERENCES public.performance_rating (performance_rating_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: event_fk | type: CONSTRAINT --
-- ALTER TABLE public.personal_event_rating DROP CONSTRAINT IF EXISTS event_fk CASCADE;
ALTER TABLE public.personal_event_rating ADD CONSTRAINT event_fk FOREIGN KEY (event_id_event)
REFERENCES public.event (event_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: location_fk | type: CONSTRAINT --
-- ALTER TABLE public.location_rating DROP CONSTRAINT IF EXISTS location_fk CASCADE;
ALTER TABLE public.location_rating ADD CONSTRAINT location_fk FOREIGN KEY (location_id_location)
REFERENCES public.location (location_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: personal_event_rating_fk | type: CONSTRAINT --
-- ALTER TABLE public.location_rating DROP CONSTRAINT IF EXISTS personal_event_rating_fk CASCADE;
ALTER TABLE public.location_rating ADD CONSTRAINT personal_event_rating_fk FOREIGN KEY (personal_event_rating_id_personal_event_rating)
REFERENCES public.personal_event_rating (personal_event_rating_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: personal_event_rating_fk | type: CONSTRAINT --
-- ALTER TABLE public.restroom_rating DROP CONSTRAINT IF EXISTS personal_event_rating_fk CASCADE;
ALTER TABLE public.restroom_rating ADD CONSTRAINT personal_event_rating_fk FOREIGN KEY (personal_event_rating_id_personal_event_rating)
REFERENCES public.personal_event_rating (personal_event_rating_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: personal_event_rating_fk | type: CONSTRAINT --
-- ALTER TABLE public.security_rating DROP CONSTRAINT IF EXISTS personal_event_rating_fk CASCADE;
ALTER TABLE public.security_rating ADD CONSTRAINT personal_event_rating_fk FOREIGN KEY (personal_event_rating_id_personal_event_rating)
REFERENCES public.personal_event_rating (personal_event_rating_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: personal_event_rating_fk | type: CONSTRAINT --
-- ALTER TABLE public.sound_rating DROP CONSTRAINT IF EXISTS personal_event_rating_fk CASCADE;
ALTER TABLE public.sound_rating ADD CONSTRAINT personal_event_rating_fk FOREIGN KEY (personal_event_rating_id_personal_event_rating)
REFERENCES public.personal_event_rating (personal_event_rating_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: personal_event_rating_fk | type: CONSTRAINT --
-- ALTER TABLE public.wardrobe_rating DROP CONSTRAINT IF EXISTS personal_event_rating_fk CASCADE;
ALTER TABLE public.wardrobe_rating ADD CONSTRAINT personal_event_rating_fk FOREIGN KEY (personal_event_rating_id_personal_event_rating)
REFERENCES public.personal_event_rating (personal_event_rating_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: event_fk | type: CONSTRAINT --
-- ALTER TABLE public.event_rating DROP CONSTRAINT IF EXISTS event_fk CASCADE;
ALTER TABLE public.event_rating ADD CONSTRAINT event_fk FOREIGN KEY (event_id_event)
REFERENCES public.event (event_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: personal_event_rating_fk | type: CONSTRAINT --
-- ALTER TABLE public.gastronomy_rating DROP CONSTRAINT IF EXISTS personal_event_rating_fk CASCADE;
ALTER TABLE public.gastronomy_rating ADD CONSTRAINT personal_event_rating_fk FOREIGN KEY (personal_event_rating_id_personal_event_rating)
REFERENCES public.personal_event_rating (personal_event_rating_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: personal_event_rating_fk | type: CONSTRAINT --
-- ALTER TABLE public.atmosphere_rating DROP CONSTRAINT IF EXISTS personal_event_rating_fk CASCADE;
ALTER TABLE public.atmosphere_rating ADD CONSTRAINT personal_event_rating_fk FOREIGN KEY (personal_event_rating_id_personal_event_rating)
REFERENCES public.personal_event_rating (personal_event_rating_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: artist_fk | type: CONSTRAINT --
-- ALTER TABLE public.performance DROP CONSTRAINT IF EXISTS artist_fk CASCADE;
ALTER TABLE public.performance ADD CONSTRAINT artist_fk FOREIGN KEY (artist_id_artist)
REFERENCES public.artist (artist_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: event_fk | type: CONSTRAINT --
-- ALTER TABLE public.performance DROP CONSTRAINT IF EXISTS event_fk CASCADE;
ALTER TABLE public.performance ADD CONSTRAINT event_fk FOREIGN KEY (event_id_event)
REFERENCES public.event (event_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: performance_rating_fk | type: CONSTRAINT --
-- ALTER TABLE public.performance DROP CONSTRAINT IF EXISTS performance_rating_fk CASCADE;
ALTER TABLE public.performance ADD CONSTRAINT performance_rating_fk FOREIGN KEY (performance_rating_id_performance_rating)
REFERENCES public.performance_rating (performance_rating_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --


